-- Esquema inicial de MYPEs Platform.
-- Refleja el esquema real generado hasta ahora por Hibernate ddl-auto=update
-- (incluye el fix manual de tbl_usuarios.email aplicado directo en la BD de dev).
-- A partir de esta migracion, ddl-auto pasa a "validate": Hibernate ya no
-- modifica el esquema solo, todo cambio futuro va en un V2__, V3__, etc.

CREATE TABLE tbl_usuarios (
    usuario_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    varchar(255) NOT NULL UNIQUE,
    email       varchar(255) NOT NULL UNIQUE,
    password    varchar(255) NOT NULL,
    rol         varchar(255) NOT NULL CHECK (rol IN ('ADMIN', 'CLIENTE'))
);

CREATE TABLE tbl_tienda (
    tienda_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     varchar(255) NOT NULL UNIQUE,
    direccion  varchar(255) NOT NULL UNIQUE,
    telefono   varchar(255) NOT NULL UNIQUE,
    latitud    double precision,
    longitud   double precision,
    imagen_url varchar(255),
    usuario_id bigint UNIQUE REFERENCES tbl_usuarios(usuario_id)
);

CREATE TABLE tbl_producto (
    producto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      varchar(255) NOT NULL,
    precio      double precision NOT NULL,
    stock       integer NOT NULL,
    imagen_url  varchar(255),
    tienda_id   bigint REFERENCES tbl_tienda(tienda_id),
    usuario_id  bigint REFERENCES tbl_usuarios(usuario_id)
);

CREATE TABLE tbl_valoracion (
    valoracion_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estrellas      integer NOT NULL,
    comentario     varchar(1000),
    fecha          timestamp(6),
    tienda_id      bigint NOT NULL REFERENCES tbl_tienda(tienda_id),
    usuario_id     bigint NOT NULL REFERENCES tbl_usuarios(usuario_id)
);

CREATE TABLE tbl_pedidos (
    pedido_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad      integer NOT NULL,
    estado_pedido varchar(255) NOT NULL CHECK (estado_pedido IN ('DISPONIBLE', 'BAJO', 'NO_DISPONIBLE')),
    usuario_id    bigint REFERENCES tbl_usuarios(usuario_id)
);

CREATE TABLE tbl_detallespedidos (
    detallespedidos_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad            integer,
    precio_unitario     double precision,
    pedido_id           bigint REFERENCES tbl_pedidos(pedido_id),
    producto_id         bigint REFERENCES tbl_producto(producto_id)
);
